[package]
name = "luca"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
relm4 = "0.8.0"
relm4-components = "0.8.0"
granite = { version = "1.1", package = "granite-rs", features = ["v7_2"] }
duplicate = "2.0.0"
clap = { version = "4.5.23", features = ["derive"] }
num-rational = "0.4.2"
num-traits = "0.2.19"
num-bigint = "0.4.6"
compact_str = "0.9.0"
pretty_dtoa = { git = "https://github.com/0xfalafel/pretty_dtoa.git", branch = "group_digits" }

[build-dependencies]
glib-build-tools = "0.17.10"
